# Generated by Django 5.0.9 on 2025-03-20 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0003_studentrialsessionreservation_studenttrialsession'),
        ('users', '0009_alter_teacher_zoom_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content', models.TextField(verbose_name='Content')),
                ('rate', models.IntegerField(help_text='Rate from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate')),
                ('session_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='timetables.sessionslot', verbose_name='Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='users.student', verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reports', to='users.teacher', verbose_name='Teacher')),
            ],
        ),
    ]
