# Generated by Django 5.0.9 on 2025-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionreport',
            name='content',
            field=models.JSONField(verbose_name='Content'),
        ),
    ]
