# Generated by Django 5.0.9 on 2025-10-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_studentsessionreport_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsessionreport',
            name='teacher',
        ),
    ]
