# Generated by Django 5.0.9 on 2025-01-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionslot',
            name='zoom_meeting_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sessionslot',
            name='zoom_meeting_link',
            field=models.URLField(default='', max_length=500),
        ),
    ]
