# Generated by Django 5.0.9 on 2025-03-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_sessionslot_zoom_meeting_id_and_more'),
        ('users', '0009_alter_teacher_zoom_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudenTrialSessionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_times', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_trial_session_reservations', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTrialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Joined', 'Joined'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zoom_meeting_id', models.CharField(default='', max_length=255)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_trial_session', to='timetables.studentrialsessionreservation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_trial_sessions', to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_trial_sessions', to='users.teacher')),
            ],
        ),
    ]
