# Generated by Django 5.0.9 on 2025-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_period_days',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_trial',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Is this a group session?'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='session_duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes for each session'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sessions_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Sessions Count'),
            preserve_default=False,
        ),
    ]
