# Generated by Django 5.0.9 on 2024-09-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_family_options_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'Unknown'), ('S', 'Student'), ('T', 'Teacher'), ('P', 'Parent')], default='U', max_length=1, verbose_name='Role'),
        ),
    ]
