# Generated by Django 5.0.9 on 2025-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_name_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='zoom_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
