# Generated by Django 5.0.9 on 2025-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teacher_zoom_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='zoom_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
