# Generated by Django 5.0.9 on 2025-07-25 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_teacher_zoom_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At'),
            preserve_default=False,
        ),
    ]
