# Generated by Django 5.0.9 on 2025-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_student_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'Unknown'), ('A', 'Admin'), ('S', 'Student'), ('T', 'Teacher'), ('P', 'Parent')], default='U', max_length=1, verbose_name='Role'),
        ),
    ]
