volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  frontend_data: {}

  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: kaleem_production_django
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://backend.kaleem.academy/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: kaleem_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: kaleem_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../compose/production/frontend/Dockerfile
    image: kaleem_production_frontend
    container_name: kaleem_production_frontend
    volumes:
      - frontend_data:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:6969:80"

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  celeryworker:
    <<: *django
    image: kaleem_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: kaleem_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: kaleem_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
