# Generated by Django 5.0.9 on 2025-07-25 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedresource',
            unique_together={('teacher', 'student', 'resource')},
        ),
    ]
