/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AuthLogoutImport } from './routes/_auth/logout'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthRegisterTeacherImport } from './routes/_auth/register/teacher'
import { Route as AuthRegisterStudentImport } from './routes/_auth/register/student'
import { Route as AuthRegisterParentImport } from './routes/_auth/register/parent'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AuthLogoutRoute = AuthLogoutImport.update({
  id: '/_auth/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterTeacherRoute = AuthRegisterTeacherImport.update({
  id: '/_auth/register/teacher',
  path: '/register/teacher',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterStudentRoute = AuthRegisterStudentImport.update({
  id: '/_auth/register/student',
  path: '/register/student',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterParentRoute = AuthRegisterParentImport.update({
  id: '/_auth/register/parent',
  path: '/register/parent',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_auth/register/parent': {
      id: '/_auth/register/parent'
      path: '/register/parent'
      fullPath: '/register/parent'
      preLoaderRoute: typeof AuthRegisterParentImport
      parentRoute: typeof rootRoute
    }
    '/_auth/register/student': {
      id: '/_auth/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof AuthRegisterStudentImport
      parentRoute: typeof rootRoute
    }
    '/_auth/register/teacher': {
      id: '/_auth/register/teacher'
      path: '/register/teacher'
      fullPath: '/register/teacher'
      preLoaderRoute: typeof AuthRegisterTeacherImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/': typeof AppIndexRoute
  '/register/parent': typeof AuthRegisterParentRoute
  '/register/student': typeof AuthRegisterStudentRoute
  '/register/teacher': typeof AuthRegisterTeacherRoute
}

export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/': typeof AppIndexRoute
  '/register/parent': typeof AuthRegisterParentRoute
  '/register/student': typeof AuthRegisterStudentRoute
  '/register/teacher': typeof AuthRegisterTeacherRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_app/': typeof AppIndexRoute
  '/_auth/register/parent': typeof AuthRegisterParentRoute
  '/_auth/register/student': typeof AuthRegisterStudentRoute
  '/_auth/register/teacher': typeof AuthRegisterTeacherRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/logout'
    | '/'
    | '/register/parent'
    | '/register/student'
    | '/register/teacher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/'
    | '/register/parent'
    | '/register/student'
    | '/register/teacher'
  id:
    | '__root__'
    | '/_app'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_app/'
    | '/_auth/register/parent'
    | '/_auth/register/student'
    | '/_auth/register/teacher'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterParentRoute: typeof AuthRegisterParentRoute
  AuthRegisterStudentRoute: typeof AuthRegisterStudentRoute
  AuthRegisterTeacherRoute: typeof AuthRegisterTeacherRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterParentRoute: AuthRegisterParentRoute,
  AuthRegisterStudentRoute: AuthRegisterStudentRoute,
  AuthRegisterTeacherRoute: AuthRegisterTeacherRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_auth/login",
        "/_auth/logout",
        "/_auth/register/parent",
        "/_auth/register/student",
        "/_auth/register/teacher"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_auth/logout": {
      "filePath": "_auth/logout.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_auth/register/parent": {
      "filePath": "_auth/register/parent.tsx"
    },
    "/_auth/register/student": {
      "filePath": "_auth/register/student.tsx"
    },
    "/_auth/register/teacher": {
      "filePath": "_auth/register/teacher.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
