name: Build and Deploy to Lightsail

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Normalize image name (lowercase)
      run: echo "IMAGE_NAME_LC=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t $REGISTRY/$IMAGE_NAME_LC:latest .

    - name: Push Docker image
      run: docker push $REGISTRY/$IMAGE_NAME_LC:latest

    - name: SSH into Lightsail and Deploy
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /home/admin/Kaleem/kaleem
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
          sudo docker compose -f ./docker-compose.production.yml pull
          sudo docker compose -f ./docker-compose.production.yml up -d
