name: Deploy to Amazon Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into Lightsail and Deploy
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /home/admin/Kaleem/kaleem
          sudo git pull origin master
          sudo docker compose -f ./kaleem/docker-compose.production.yml up --build -d 
